name: VC

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
env:
  GitHubMail: ${{ secrets.GitHubMail }}
  GitHubName: ${{ secrets.GitHubName }}

jobs:
  debug:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set Git Configs & Secrets
        run: |
          sudo apt-get install -y git
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Clone The Secret Mirror Repository
        continue-on-error: true
        run: |
          git clone https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.repo }} source
          cd source
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t vcbot 

      - name: running VC bot
        timeout-minutes: 338
        continue-on-error: true
        run: |
          cd source
          docker run --privileged --rm -i --env-file .env vcbot

      - name: Loop Workflow
        continue-on-error: false
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          cd source
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
          git add looper.txt
          git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY}
