name: VC

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:
   
jobs:
  debug:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: running VC bot
        timeout-minutes: 300
        continue-on-error: true
        run: |
          echo "${{ secrets.GH_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker run --privileged --rm -i docker.pkg.github.com/carbonatedblack/vcbot/vclatest:latest

      - name: Loop Workflow
        continue-on-error: true
        run: curl -X POST --header "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/debug.yml/dispatches -d '{"ref":"main"}'
